"""Choose which API changes to probe when there are more than the budget allows.

Ranking favours changes that are most likely to bite this project: symbols the project's own
code already touches, hard breaks over soft ones, top-level exports over deep internals, and
changes that recur across many call sites. Near-duplicates are probed once, and the budget is
shared round-robin across packages so one huge migration cannot crowd out everything else.

What the code touches is judged per package, from the files that import it
(:meth:`since_cutoff.project.Project.code_use`): ``files`` below is that list, empty for a
package the code does not import.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import replace
from typing import NamedTuple

from since_cutoff.apidiff import (
    DEPRECATED,
    KIND_PRIORITY,
    MOVED,
    PARAM_KEYWORD_ONLY,
    PARAM_POSITIONAL_ONLY,
    PARAM_REQUIRED,
    REMOVED,
    APIChange,
    is_beta_segment,
)
from since_cutoff.project import FileUse

# How used_names found a change in the project's code (see match): through one of its paths,
# or, for a change from a diff made before DIFF_SCHEMA 12 (no import paths), by its package
# and name only, which the "your code uses" mark then says.
PATH_MATCH = "path"
NAME_MATCH = "name"
MATCHED_BY_NAME = "matched by name"

# How the project's code uses a changed API (form): as the release at the cutoff allowed and
# the pinned one no longer does, or only uses the API (the line is fine today, but an assistant
# editing it may add the old form). A static name match: nothing is run.
OLD_FORM = "old_form"
USES_API = "uses_api"
FORM_LABELS = {OLD_FORM: "old form", USES_API: "uses this API"}
# What a use of a change is (Use.kind), most specific first: the changed parameter passed to its
# callable; a call of it (or of its class); a read of it on its class or an instance; a name the
# file imports or reads on a module.
USE_KEYWORD = "keyword"
USE_CALL = "call"
USE_MEMBER = "member"
USE_REFERENCE = "reference"
_USE_ORDER = {USE_KEYWORD: 0, USE_CALL: 1, USE_MEMBER: 2, USE_REFERENCE: 3}
# Changes whose use is never the old form yet: a static match cannot tell whether a call
# passes a now-required, keyword-only or positional-only parameter the right way.
_NEVER_OLD_FORM = (PARAM_REQUIRED, PARAM_KEYWORD_ONLY, PARAM_POSITIONAL_ONLY)


class Use(NamedTuple):
    """Where the project's code uses a change (:func:`uses`).

    File-level for now: ``line`` and ``column`` (1-based and 0-based) stay None until the scan
    records where in the file each name is used (issue #8, ``FileUse.sites``); the reports
    show ``app/main.py`` until then, and ``app/main.py:7`` with them.
    """

    file: str  # relative to the project root, with "/" ("" when unknown)
    line: int | None
    column: int | None
    kind: str  # USE_*
    names: tuple[str, ...]  # as used_names gives them: (callable,) or (callable, parameter)
    how: str = PATH_MATCH  # PATH_MATCH, or NAME_MATCH for a change without import paths
    form: str = USES_API  # OLD_FORM when this use is the old form of the change (form())

    @property
    def where(self) -> str:
        """``app/main.py``, ``app/main.py:7`` once lines are known."""
        return f"{self.file}:{self.line}" if self.line is not None else self.file


# Where a change made by collapse() keeps the changes it merged (as PackageScan keeps its
# collapsed changes): not a field, so not in to_dict() or results.json.
_MERGED = "_merged"

_NOISE_NAMES = {"__version__", "__all__", "version", "VERSION"}
# Module metadata, including what version files generated by setuptools-scm or hatch-vcs define.
_METADATA_NAMES = {"__version__", "__all__", "__version_tuple__", "version_tuple", "VERSION_TUPLE"}
# Modules that application code rarely imports directly.
_SIDE_SEGMENTS = {"cli", "commands", "test", "testing", "experimental"}
# Integration and implementation layers: type-checker plugins (pydantic.mypy), compatibility
# shims, protocol adapters (polars.interchange) and per-backend code (sqlalchemy.dialects).
_INTERNAL_SEGMENTS = {
    "compat",
    "connectors",
    "dialects",
    "interchange",
    "internal",
    "internals",
    "mypy",
    "plugin",
    "plugins",
}


def score(change: APIChange, files: Sequence[FileUse] = ()) -> float:
    s = 10.0 - 1.5 * KIND_PRIORITY.get(change.kind, 6)
    s += 3.0 * usage(change, files)
    if change.owner and any(_names_class(change, f) for f in files):
        s += 2.0
    depth = change.path.count(".")
    s += max(0.0, 3.0 - 0.75 * depth)
    s += min(2.0, math.log2(change.occurrences + 1) - 1)
    if change.old_doc:
        s += 1.0
    if change.hint:
        s += 0.5
    if change.name in _NOISE_NAMES or (change.name.isupper() and change.owner):
        s -= 4.0  # enum members and constants rarely matter
    segments = change.path.split(".")[1:-1]  # modules (and owner), not the package or name
    if any(seg in _INTERNAL_SEGMENTS for seg in segments):
        s -= 3.0
    elif any(seg in _SIDE_SEGMENTS for seg in segments):
        s -= 2.0
    if (
        change.path.count(".") == 1
        and change.kind in ("removed", "moved")
        and change.old_signature
        and change.old_signature.startswith("module ")
    ):
        s -= 1.0
    return s


def rank(changes: Iterable[APIChange], files: Sequence[FileUse] = ()) -> list[APIChange]:
    return sorted(changes, key=lambda c: (-score(c, files), c.path, c.parameter or ""))


def collapse(changes: Iterable[APIChange]) -> list[APIChange]:
    """One entry per change, most useful first.

    The same change is often reachable under several public paths (``pkg.f`` and
    ``pkg.module.f``); it is listed once, under its shortest path, with the others counted as
    similar. Module metadata such as ``__version__`` is dropped.
    """
    ordered = sorted(
        changes, key=lambda c: (-score(c), c.path.count("."), c.path, c.parameter or "")
    )
    firsts: dict[str, APIChange] = {}
    merged: dict[str, list[APIChange]] = {}
    for c in ordered:
        if c.name in _METADATA_NAMES:
            continue
        key = c.concept_key
        rep = firsts.get(key)
        if rep is None:
            firsts[key] = replace(c, also=list(c.also))
            merged[key] = []
        else:
            rep.occurrences += c.occurrences
            rep.also = [*rep.also, c.path, *c.also][:5]  # to show: "also removed under ..."
        merged[key] += _merged(c)
    for key, rep in firsts.items():
        # The project's code is matched against each merged change (used_names), and the
        # collapsed change lists every path of them all, whatever ``also`` shows.
        rep.__dict__[_MERGED] = merged[key]
        if any(c.import_paths is not None for c in merged[key]):
            every = {p for c in merged[key] for p in paths(c)}
            rep.import_paths = sorted(every, key=lambda p: (p.count("."), p))
    return list(firsts.values())


def _merged(change: APIChange) -> list[APIChange]:
    """The changes :func:`collapse` merged into ``change``, or ``[change]``."""
    return list(change.__dict__.get(_MERGED) or [change])


def other_paths_text(change: APIChange, *, example: bool = True) -> str:
    """The other public paths of the same change (see :func:`collapse`): ``also removed under
    12 other paths, e.g. `setuptools.command.alias.alias.ensure_string_list` ``, or "".

    Not "similar": that would read like a replacement, and it names another removed path.
    """
    n = change.occurrences - 1
    if n < 1:
        return ""
    verb = {REMOVED: "removed", MOVED: "moved", DEPRECATED: "deprecated"}.get(
        change.kind, "changed"
    )
    e_g = f", e.g. `{change.also[0]}`" if example and change.also else ""
    return f"also {verb} under {n} other path{'' if n == 1 else 's'}{e_g}"


def used_names(change: APIChange, files: Sequence[FileUse]) -> tuple[str, ...]:
    """The names of a change that the project's code uses, judged file by file.

    ``()``, ``(callable,)`` or ``(callable, parameter)``, from the files that import the
    change's package (``files``). A module-level name counts when a file imports it, or reads
    it on an imported module, under one of the change's paths (:func:`paths`, re-exports
    included: ``from huggingface_hub import hf_hub_download`` for a change to
    ``huggingface_hub.file_download.hf_hub_download``): ``copier.asdict`` is not the
    ``asdict`` of ``from dataclasses import asdict``. A method or attribute counts when a file
    reads it on its class (under one of those paths), on what the file shows is an instance of
    the class (``app = Starlette(...)`` and ``app.routes``, ``self.routes`` in a subclass), or
    on an attribute named after the class (``client.messages.create`` for ``Messages.create``);
    not on any value (``self.middleware`` of the project's own class). A constructor counts
    when a file calls the class. A changed parameter counts only when it is
    passed by keyword to its callable: ``resume_download=`` passed to ``hf_hub_download`` says
    nothing about ``snapshot_download(resume_download=...)``.

    A change from a diff made before DIFF_SCHEMA 12 has no import paths; for it, a path of the
    same package with the same last name counts too (:func:`match` says "name").
    """
    return _best(change, files)[0]


def match(change: APIChange, files: Sequence[FileUse]) -> str | None:
    """How :func:`used_names` found the change in the project's code: PATH_MATCH (through one
    of its paths), NAME_MATCH (only by its package and name, for a change without import
    paths), or None when the code does not use it."""
    return _best(change, files)[1]


def paths(change: APIChange) -> list[str]:
    """Every path of a change that the project's code may import or read it under: its own,
    the other paths it was merged with (all of them, where ``also`` keeps 5 to show) and the
    re-exports the diff recorded (APIChange.import_paths)."""
    return list(dict.fromkeys((change.path, *change.also, *(change.import_paths or ()))))


def _best(change: APIChange, files: Sequence[FileUse]) -> tuple[tuple[str, ...], str | None]:
    """The most names any one file uses, and how they were matched (a path before a name).

    A collapsed change is matched as each of the changes it merged (a sync/async twin, a
    beta mirror, the same class under another module), each with its own owner and paths.
    """
    if not files:
        return (), None
    merged = _with_paths(change)
    found = [_in_file(merged, f) for f in files]
    for how in (PATH_MATCH, NAME_MATCH):
        best: tuple[str, ...] = ()
        for _, names, matched in found:
            if matched == how and len(names) > len(best):
                best = names
        if best:
            return best, how
    return (), None


def _with_paths(change: APIChange) -> list[tuple[APIChange, frozenset[str]]]:
    """The changes a (collapsed) change stands for, each with its paths (:func:`paths`)."""
    return [(c, frozenset(paths(c))) for c in _merged(change)]


def _in_file(
    merged: list[tuple[APIChange, frozenset[str]]], f: FileUse
) -> tuple[APIChange | None, tuple[str, ...], str | None]:
    """The names of a change that one file uses, the merged change they are of, and how they
    were matched: through a path (PATH_MATCH), else, for a change without import paths, by its
    package and name (NAME_MATCH)."""
    best: tuple[APIChange | None, tuple[str, ...]] = (None, ())
    for c, by_path in merged:
        names = _used_in(c, f, by_path)
        if len(names) > len(best[1]):
            best = (c, names)
    if best[1]:
        return best[0], best[1], PATH_MATCH
    for c, _ in merged:
        if c.import_paths is not None:
            continue  # the diff recorded its paths: the name alone is not enough
        names = _used_in(c, f, frozenset(_same_name(c, f)))
        if len(names) > len(best[1]):
            best = (c, names)
    return best[0], best[1], NAME_MATCH if best[1] else None


def uses(change: APIChange, files: Sequence[FileUse]) -> list[Use]:
    """Where the project's code uses a change: one :class:`Use` per file that uses it (the
    most names that file uses, as :func:`used_names` counts them), most specific first (a
    keyword, a call, a member, a reference), then by file.

    File-level for now (``Use.line`` is None): recording each site's line and column is
    issue #8, after which each file can give several uses, still most specific first.
    """
    if not files:
        return []
    merged = _with_paths(change)
    found = []
    for f in files:
        c, names, how = _in_file(merged, f)
        if c is not None and how is not None:
            kind = _use_kind(c, f, names)
            found.append(Use(f.file, None, None, kind, names, how, form(change, names)))
    return ordered(found)


def ordered(found: Iterable[Use]) -> list[Use]:
    """Uses (of one change, or of all the changes of one API) each once, most specific first,
    then by file and line."""
    return sorted(
        dict.fromkeys(found),
        key=lambda u: (_USE_ORDER.get(u.kind, 9), u.file, u.line or 0, u.names),
    )


def _use_kind(change: APIChange, f: FileUse, names: tuple[str, ...]) -> str:
    if len(names) == 2:
        return USE_KEYWORD
    if names[0] in f.calls:
        return USE_CALL
    return USE_MEMBER if change.owner else USE_REFERENCE


def form(change: APIChange, names: tuple[str, ...]) -> str:
    """Whether code that uses these names of a change (:func:`used_names`) uses it in the
    old form (OLD_FORM) or only uses the API (USES_API).

    Old form: it reads or imports what was removed, moved (its old path) or changed kind, uses
    what is deprecated, or passes a removed or deprecated parameter by keyword to its callable.
    A parameter that is now required, keyword-only or positional-only is always "uses this
    API": whether a call passes it the new way is not something a name match can tell. So is a
    function whose deprecation covers one of its call forms (an ``@overload``) only.
    """
    if not names or change.kind in _NEVER_OLD_FORM or change.call_form:
        return USES_API
    if change.parameter:
        return OLD_FORM if len(names) == 2 else USES_API
    return OLD_FORM


def _same_name(change: APIChange, f: FileUse) -> list[str]:
    """Paths the file reaches in the change's package that end in the change's name (the
    name of its class, for a member), as paths of the change."""
    root = change.path.split(".", 1)[0]
    last = change.owner or change.name
    found = [p for p in f.paths if p.split(".", 1)[0] == root and p.rsplit(".", 1)[-1] == last]
    return sorted(f"{p}.{change.name}" for p in found) if change.owner else sorted(found)


def _used_in(change: APIChange, f: FileUse, by_path: frozenset[str]) -> tuple[str, ...]:
    """The names of ``change`` that file ``f`` uses, through the paths ``by_path``.

    A changed parameter counts only when the file passes it to this very callable: to a call
    the file shows is of one of those paths (FileUse.keyword_paths), or, for a method matched
    by its attribute name (``client.messages.create``), to a call at the end of such a chain
    (FileUse.keyword_chains). ``temperature=`` passed to another library's ``create`` in the
    same file is not the old form of ``Messages.create``."""
    owner, name = change.owner, change.name
    parameter = change.parameter
    wanted = parameter if parameter and not parameter.startswith("__") else None
    passed = False
    if not owner:
        found = sorted(f.paths & by_path, key=lambda p: (p.rsplit(".", 1)[-1] != name, p))
        if not found:
            return ()
        # The name the file imports it under (a package may re-export it under another).
        callable_name = found[0].rsplit(".", 1)[-1]
        passed = wanted is not None and any((p, wanted) in f.keyword_paths for p in by_path)
    elif name == "__init__":
        named = {path.rsplit(".", 1)[0] for path in by_path} & f.paths
        if not named:
            return ()
        # The class called under any of its names: ``AsyncClient`` for a change merged with
        # its sync twin's, ``HubClient`` where a package re-exports ``Client`` under that name.
        others = sorted(c.rsplit(".", 1)[-1] for c in named)
        called = [c for c in dict.fromkeys([owner, *others]) if c in f.calls]
        if not called:
            return ()
        classes = {path.rsplit(".", 1)[0] for path in by_path}
        through = sorted(c for c in classes if (c, wanted) in f.keyword_paths) if wanted else []
        passed = bool(through)
        callable_name = through[0].rsplit(".", 1)[-1] if through else called[0]
    else:
        if name.startswith("__") or name not in f.attributes:
            return ()
        on_class = any((path.rsplit(".", 1)[0], name) in f.members for path in by_path)
        by_pair = _pair_chains(change, f)
        if not (on_class or by_pair):
            return ()
        callable_name = name
        if wanted is not None:
            passed = (on_class and any((p, wanted) in f.keyword_paths for p in by_path)) or any(
                (chain, wanted) in f.keyword_chains for chain in by_pair
            )
    if passed and parameter:
        return (callable_name, parameter)
    return (callable_name,)


def _pair_chains(change: APIChange, f: FileUse) -> list[str]:
    """The chains of the file that reach a method or attribute by the attribute named after
    its class (``client.messages.create`` for ``Messages.create``), with ``beta`` in them
    when the change is to an SDK's beta mirror (APIChange.in_beta) and without it otherwise:
    ``client.beta.messages.create`` is not ``Messages.create`` of ``resources.messages``."""
    pair = f"{(change.owner or '').lower()}.{change.name}"
    if pair not in f.pairs:
        return []
    found = []
    for chain in f.chains:
        parts = chain.split(".")
        beta = any(is_beta_segment(p) for p in parts[:-2])
        if ".".join(parts[-2:]) == pair and beta == change.in_beta:
            found.append(chain)
    return found


def _names_class(change: APIChange, f: FileUse) -> bool:
    """Whether the file imports (or reads on an imported module) the class that owns a
    method or attribute change, under one of the change's paths."""
    return any(path.rsplit(".", 1)[0] in f.paths for c in _merged(change) for path in paths(c))


def usage(change: APIChange, files: Sequence[FileUse] = ()) -> int:
    """How directly the project's code touches a change.

    2: it names exactly what changed (the changed name, or a callable and its changed
    parameter); 1: it names the callable but not the changed parameter; 0: neither.
    """
    names = used_names(change, files)
    if not names:
        return 0
    return 2 if len(names) == 2 or not change.parameter else 1


def used_name(change: APIChange, files: Sequence[FileUse]) -> str | None:
    """The most specific name of the change that the project's code uses, if any."""
    names = used_names(change, files)
    return names[-1] if names else None


def uses_text(change: APIChange, files: Sequence[FileUse]) -> str | None:
    """The names for a "your code uses ..." mark, as Markdown code (None if it uses none),
    with ", matched by name" when only the package and name matched (:func:`match`)."""
    names, how = _best(change, files)
    if not names:
        return None
    text = " and ".join(f"`{n}`" for n in names)
    return f"{text}, {MATCHED_BY_NAME}" if how == NAME_MATCH else text


def project_rank(change: APIChange, files: Sequence[FileUse]) -> tuple[int, bool, float, str]:
    """Sort key for one package's changes as seen from a project.

    What the code uses comes first (a callable and its changed parameter before the callable
    alone), then hard breaks before deprecations, then the score.
    """
    return (
        -usage(change, files),
        change.kind == DEPRECATED,
        -score(change, files),
        change.path,
    )


def select(
    changes_by_package: dict[str, list[APIChange]],
    files_by_package: Mapping[str, Sequence[FileUse]],
    budget: int,
) -> list[APIChange]:
    """Pick up to ``budget`` changes, one per concept, spread round-robin across packages.

    ``files_by_package``: the files of the project's code that import each package.
    """
    queues: dict[str, list[APIChange]] = {}
    for package, changes in changes_by_package.items():
        seen: set[str] = set()
        queue: list[APIChange] = []
        for c in rank(changes, files_by_package.get(package, ())):
            if c.concept_key in seen:
                continue
            seen.add(c.concept_key)
            queue.append(c)
        if queue:
            queues[package] = queue
    # Packages whose best change scores highest go first in each round.
    order = sorted(queues, key=lambda p: -score(queues[p][0], files_by_package.get(p, ())))
    picked: list[APIChange] = []
    while len(picked) < budget and any(queues.values()):
        for package in order:
            if queues[package] and len(picked) < budget:
                picked.append(queues[package].pop(0))
    return picked
