"""Choose which API changes to probe when there are more than the budget allows.

Ranking favours changes that are most likely to bite this project: symbols the project's own
code already touches, hard breaks over soft ones, top-level exports over deep internals, and
changes that recur across many call sites. Near-duplicates are probed once, and the budget is
shared round-robin across packages so one huge migration cannot crowd out everything else.

What the code touches is judged per package, from the files that import it
(:meth:`since_cutoff.project.Project.code_use`): ``files`` below is that list, empty for a
package the code does not import.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import replace

from since_cutoff.apidiff import DEPRECATED, KIND_PRIORITY, MOVED, REMOVED, APIChange
from since_cutoff.project import FileUse

_NOISE_NAMES = {"__version__", "__all__", "version", "VERSION"}
# Module metadata, including what version files generated by setuptools-scm or hatch-vcs define.
_METADATA_NAMES = {"__version__", "__all__", "__version_tuple__", "version_tuple", "VERSION_TUPLE"}
# Modules that application code rarely imports directly.
_SIDE_SEGMENTS = {"cli", "commands", "test", "testing", "experimental"}
# Integration and implementation layers: type-checker plugins (pydantic.mypy), compatibility
# shims, protocol adapters (polars.interchange) and per-backend code (sqlalchemy.dialects).
_INTERNAL_SEGMENTS = {
    "compat",
    "connectors",
    "dialects",
    "interchange",
    "internal",
    "internals",
    "mypy",
    "plugin",
    "plugins",
}


def score(change: APIChange, files: Sequence[FileUse] = ()) -> float:
    s = 10.0 - 1.5 * KIND_PRIORITY.get(change.kind, 6)
    s += 3.0 * usage(change, files)
    if change.owner and any(_names_class(change, f) for f in files):
        s += 2.0
    depth = change.path.count(".")
    s += max(0.0, 3.0 - 0.75 * depth)
    s += min(2.0, math.log2(change.occurrences + 1) - 1)
    if change.old_doc:
        s += 1.0
    if change.hint:
        s += 0.5
    if change.name in _NOISE_NAMES or (change.name.isupper() and change.owner):
        s -= 4.0  # enum members and constants rarely matter
    segments = change.path.split(".")[1:-1]  # modules (and owner), not the package or name
    if any(seg in _INTERNAL_SEGMENTS for seg in segments):
        s -= 3.0
    elif any(seg in _SIDE_SEGMENTS for seg in segments):
        s -= 2.0
    if (
        change.path.count(".") == 1
        and change.kind in ("removed", "moved")
        and change.old_signature
        and change.old_signature.startswith("module ")
    ):
        s -= 1.0
    return s


def rank(changes: Iterable[APIChange], files: Sequence[FileUse] = ()) -> list[APIChange]:
    return sorted(changes, key=lambda c: (-score(c, files), c.path, c.parameter or ""))


def collapse(changes: Iterable[APIChange]) -> list[APIChange]:
    """One entry per change, most useful first.

    The same change is often reachable under several public paths (``pkg.f`` and
    ``pkg.module.f``); it is listed once, under its shortest path, with the others counted as
    similar. Module metadata such as ``__version__`` is dropped.
    """
    ordered = sorted(
        changes, key=lambda c: (-score(c), c.path.count("."), c.path, c.parameter or "")
    )
    firsts: dict[str, APIChange] = {}
    for c in ordered:
        if c.name in _METADATA_NAMES:
            continue
        rep = firsts.get(c.concept_key)
        if rep is None:
            firsts[c.concept_key] = replace(c, also=list(c.also))
        else:
            rep.occurrences += c.occurrences
            rep.also = [*rep.also, c.path, *c.also][:5]
    return list(firsts.values())


def other_paths_text(change: APIChange, *, example: bool = True) -> str:
    """The other public paths of the same change (see :func:`collapse`): ``also removed under
    12 other paths, e.g. `setuptools.command.alias.alias.ensure_string_list` ``, or "".

    Not "similar": that would read like a replacement, and it names another removed path.
    """
    n = change.occurrences - 1
    if n < 1:
        return ""
    verb = {REMOVED: "removed", MOVED: "moved", DEPRECATED: "deprecated"}.get(
        change.kind, "changed"
    )
    e_g = f", e.g. `{change.also[0]}`" if example and change.also else ""
    return f"also {verb} under {n} other path{'' if n == 1 else 's'}{e_g}"


def used_names(change: APIChange, files: Sequence[FileUse]) -> tuple[str, ...]:
    """The names of a change that the project's code uses, judged file by file.

    ``()``, ``(callable,)`` or ``(callable, parameter)``, from the files that import the
    change's package (``files``). A module-level name counts when a file imports it, or reads
    it on an imported module, under one of the change's paths: ``copier.asdict`` is not the
    ``asdict`` of ``from dataclasses import asdict``. A method or attribute counts when a file
    reads it on its class (under one of those paths), on what the file shows is an instance of
    the class (``app = Starlette(...)`` and ``app.routes``, ``self.routes`` in a subclass), or
    on an attribute named after the class (``client.messages.create`` for ``Messages.create``);
    not on any value (``self.middleware`` of the project's own class). A constructor counts
    when a file calls the class. A changed parameter counts only when it is
    passed by keyword to its callable: ``resume_download=`` passed to ``hf_hub_download`` says
    nothing about ``snapshot_download(resume_download=...)``.
    """
    best: tuple[str, ...] = ()
    for f in files:
        names = _used_in(change, f)
        if len(names) > len(best):
            best = names
    return best


def _used_in(change: APIChange, f: FileUse) -> tuple[str, ...]:
    owner, name = change.owner, change.name
    if not owner:
        if not any(path in f.paths for path in (change.path, *change.also)):
            return ()
        callable_name = name
    elif name == "__init__":
        if not (owner in f.calls and _names_class(change, f)):
            return ()
        callable_name = owner
    else:
        if name.startswith("__") or name not in f.attributes:
            return ()
        on_class = any(
            (path.rsplit(".", 1)[0], name) in f.members for path in (change.path, *change.also)
        )
        if not (on_class or f"{owner.lower()}.{name}" in f.pairs):
            return ()
        callable_name = name
    parameter = change.parameter
    if parameter and not parameter.startswith("__") and (callable_name, parameter) in f.keywords:
        return (callable_name, parameter)
    return (callable_name,)


def _names_class(change: APIChange, f: FileUse) -> bool:
    """Whether the file imports (or reads on an imported module) the class that owns a
    method or attribute change, under one of the change's paths."""
    return any(path.rsplit(".", 1)[0] in f.paths for path in (change.path, *change.also))


def usage(change: APIChange, files: Sequence[FileUse] = ()) -> int:
    """How directly the project's code touches a change.

    2: it names exactly what changed (the changed name, or a callable and its changed
    parameter); 1: it names the callable but not the changed parameter; 0: neither.
    """
    names = used_names(change, files)
    if not names:
        return 0
    return 2 if len(names) == 2 or not change.parameter else 1


def used_name(change: APIChange, files: Sequence[FileUse]) -> str | None:
    """The most specific name of the change that the project's code uses, if any."""
    names = used_names(change, files)
    return names[-1] if names else None


def uses_text(change: APIChange, files: Sequence[FileUse]) -> str | None:
    """The names for a "your code uses ..." mark, as Markdown code (None if it uses none)."""
    names = used_names(change, files)
    return " and ".join(f"`{n}`" for n in names) if names else None


def project_rank(change: APIChange, files: Sequence[FileUse]) -> tuple[int, bool, float, str]:
    """Sort key for one package's changes as seen from a project.

    What the code uses comes first (a callable and its changed parameter before the callable
    alone), then hard breaks before deprecations, then the score.
    """
    return (
        -usage(change, files),
        change.kind == DEPRECATED,
        -score(change, files),
        change.path,
    )


def select(
    changes_by_package: dict[str, list[APIChange]],
    files_by_package: Mapping[str, Sequence[FileUse]],
    budget: int,
) -> list[APIChange]:
    """Pick up to ``budget`` changes, one per concept, spread round-robin across packages.

    ``files_by_package``: the files of the project's code that import each package.
    """
    queues: dict[str, list[APIChange]] = {}
    for package, changes in changes_by_package.items():
        seen: set[str] = set()
        queue: list[APIChange] = []
        for c in rank(changes, files_by_package.get(package, ())):
            if c.concept_key in seen:
                continue
            seen.add(c.concept_key)
            queue.append(c)
        if queue:
            queues[package] = queue
    # Packages whose best change scores highest go first in each round.
    order = sorted(queues, key=lambda p: -score(queues[p][0], files_by_package.get(p, ())))
    picked: list[APIChange] = []
    while len(picked) < budget and any(queues.values()):
        for package in order:
            if queues[package] and len(picked) < budget:
                picked.append(queues[package].pop(0))
    return picked
